import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const rootDir = process.cwd();
const localContentPath = path.join(rootDir, 'src', 'members-content.local.json');
const configPath = path.join(rootDir, 'src', 'config.ts');
const password = process.env.MEMBERS_PASSWORD;
const iterations = 210000;

if (!password) {
	console.error('MEMBERS_PASSWORD を指定してください。');
	console.error('例: MEMBERS_PASSWORD=your-password npm run members:encrypt');
	process.exit(1);
}

const sourceText = await fs.readFile(localContentPath, 'utf8');
const payload = JSON.parse(sourceText);
const salt = crypto.randomBytes(16);
const iv = crypto.randomBytes(12);
const key = crypto.pbkdf2Sync(password, salt, iterations, 32, 'sha256');
const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
const ciphertext = Buffer.concat([cipher.update(JSON.stringify(payload), 'utf8'), cipher.final()]);
const tag = cipher.getAuthTag();

const configSource = `// This file is generated by \`npm run members:encrypt\`.
// Do not edit the blob by hand.
export const MEMBERS_CONTENT_BLOB = {
\tsalt: '${salt.toString('base64')}',
\tiv: '${iv.toString('base64')}',
\tciphertext:
\t\t'${ciphertext.toString('base64')}',
\ttag: '${tag.toString('base64')}',
\titerations: ${iterations},
} as const;
`;

await fs.writeFile(configPath, configSource, 'utf8');
console.log('src/config.ts を更新しました。');
